import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";
import AppProvider from "./Context/AppContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppProvider>
      <Sidebar/>
      {/* {children} */}
      </AppProvider>
      </body>
    </html>
  );
}
